# Generated by Django 5.0.4 on 2024-04-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenNames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names_man", models.CharField(max_length=255)),
                ("bitrix_id", models.IntegerField(unique=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Мужской", "М")],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WomenNames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names_woman", models.CharField(max_length=255)),
                ("bitrix_id", models.IntegerField(unique=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Женский", "Ж")],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
